### PR TITLE
MME-009/feat/mentee-community-page

### PR DESCRIPTION
**Pull request by Nwonye-Michael**
created my discussion card and discussion slider container , and empty created the mentorship card and mentorship container and added my assets folder 
Screenshot 2023-10-07 010322

### CODE REVIEW

**Comment by 0laolu** [comment]
Resolve your conflicts

**Comment by Nwonye-Michael** [comment]
conflict resolved

**Comment by Nwonye-Michael** [comment]
here is the image of the new feature i added the mentor
Screenshot 2023-10-07 123101

**Review by kleenpulse — APPROVED** [review]
Good work boss

**Pull request merged**
