### PR TITLE
Men 10/feat/resources center mentee

### PR DESCRIPTION
**Pull request by RB-Isiaq**
Completed the three assigned pages.

Routes:
- /resource
- /resource/explore
- /resource/explore/:id

Screenshot 2023-10-06 154907
Screenshot 2023-10-06 155044
Screenshot 2023-10-06 155125

### CODE REVIEW

**Comment by 0laolu** [comment]
There are still files that are conflicting. Kindly resolve them

**Comment by RB-Isiaq** [comment]
> There are still files that are conflicting. Kindly resolve them

Done.
Please review and merge @0laolu

**Comment by kleenpulse** [comment]
Everything looks good, but you should fix the SVG imports

**Comment by kleenpulse** [comment]
and make another PR

**Pull request closed without merging**
